[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
authors = ["Saad Moazzam"]

[dependencies]
eframe = "0.31.0"
egui = "0.31.0"
reqwest = { version = "0.12.12", features = ["json"] }
serde = "1.0.217"
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full"] }